### ISSUE TITLE
How to test ssh-add?

### ISSUE THREAD

**Issue by edouard-lopez** [jorgebucaran/fishtape#22]
I'm having trouble testing a `ssh-add` command for the [herrbischoff/fish-ssh-agent](https://github.com/herrbischoff/fish-ssh-agent) project. So far I've tested almost everything but I feel there is some `fish`-related catch I'm not aware of.
### Source
- [test `add_keys.fish`](https://github.com/edouard-lopez/fish-ssh-agent-1/blob/0ea8c2fb20b8ec801f1aaf1c4963b6a233f3d7d1/test/add_keys.fish) ;
- [code `add_keys.fish`](https://github.com/edouard-lopez/fish-ssh-agent-1/blob/0ea8c2fb20b8ec801f1aaf1c4963b6a233f3d7d1/functions/__add_keys.fish).
### What I'm testing

```
…
ssh-add $private >/tmp/ssh-add.log ^ /tmp/ssh-add.err
…
```
### Error: what I got

```
$ fishtape test/*.fish | tap-min
Could not open a connection to your authentication agent.
Could not open a connection to your authentication agent.

    10 tests complete (9ms)
    null Add given keys
    ---
    operator: =
    expected: '0'
    received: '1'
    ...
```
### Question

Am I in some special context where `ssh-agent` is unavailable ? Or is it something else?

**Comment by jorgebucaran** [comment]
This looks like a tough one.

Do you think you'd be able to help @Markcial?

**Comment by Markcial** [comment]
I'd recommend to skip the ssh-add part by using [mock](https://github.com/fisherman/mock) library, it's not necessary to test 3rd parties implementations (except you want to test the integration).

if you still want to test integration i pushed a [branch to my repo](https://github.com/Markcial/fish-ssh-agent-1/tree/testing-ssh-agent), feel free to check it or ask for more information about the mock library usage :D

:beers:

**Comment by jorgebucaran** [comment]
Thanks @Markcial.

**Comment by edouard-lopez** [comment]
The [merged PR](https://github.com/herrbischoff/fish-ssh-agent/pull/3/files) does it [like](https://github.com/herrbischoff/fish-ssh-agent/blob/3095ffaf6e25296f6fab95bee18bf54eb7cef180/test/add_keys.fish#L22-L33):

```
test "$TEST - Add a given key"
  (
      eval (ssh-agent -c) > /dev/null
      set old_keys_list (ssh-add -l | grep --count RSA)
      ssh-keygen -f $path/.test -N '' >/dev/null

      __add_keys $path/.test.pub

      set new_keys_list (ssh-add -l | grep --count RSA)
      math "$new_keys_list - $old_keys_list"
    ) = 1
end
```

**Comment by jorgebucaran** [comment]
@edouard-lopez Wny did you close here? Did you solve the issue?

**Comment by edouard-lopez** [comment]
@jorgebucaran Yes, the code above is running correctly
