### ISSUE TITLE
Verbose

### ISSUE THREAD

**Issue by edouard-lopez** [jorgebucaran/fishtape#29]
Is there a way to have a verbose mode where one can see what's happening? Something similar to `bash -x cmd`.

I'm asking because:
1. when writing tests, I'm not sure if it's stuck or just taking some time ;
2. when test fail I lack insight of what is wrong

For instance:

```
test "install with fisher"
    'Done+WRONG_VALUE+' = (
        docker run \
            --name pure \
            --rm \
            --tty \
        edouardlopez/pure-fish 'fisher rafaelrinaldi/pure' \
        | grep --only-matching 'Done'
    )
end
```

Will throw:
```

$ fishtape tests/ci.test.fish | tap-min
type: Could not find “”

install with fisher
        operator: =
        expected: 'Done2'
        actual:   undefined

3 tests complete (9ms)
```

Disclaimer: maybe I'm not having the right approach

**Comment by jorgebucaran** [comment]
@edouard-lopez The default behavior is as verbose as you can get, and there's a -q/--quiet option to silence it.

<img width="1280" alt="screen shot 2018-09-09 at 0 02 28" src="https://user-images.githubusercontent.com/56996/45255604-abf8bd00-b3c3-11e8-9a0b-6c79b73fe837.png">

**Comment by jorgebucaran** [comment]
Instead of grep for a string, what if you check the exit code. Fisherman should fail and set $status to a non-zero value if it can't install the plugin.

**Comment by jorgebucaran** [comment]
@edouard-lopez I forgot to mention there is a `--dry-run` option. I'm not sure if it will be survive #31, but thought it was worth mentioning.
