### ISSUE TITLE
Fishtape 2

### ISSUE THREAD

**Issue by jorgebucaran** [jorgebucaran/fishtape#31]
Fishtape 2 will break the test syntax as we want to make it compatible with `fish_indent` #32, #34. 

## Summary

- Make test syntax compatible with [`fish_indent`](https://fishshell.com/docs/current/commands.html#fish_indent)
- Run test files in parallel (not assertions, but files)
- Remove `--pipe` in favor of any userland solution like `"fish -c "fishtape *.fish | tap-nyan"` 
- Remove the built-in `test` array extensions (don't know what I am talking about? don't worry then)

Here's the new test syntax I have in mind. See that `test` blocks are now gone. The `test` builtin has been "enhanced" to take an optional test description. If you already know how to use the shell's `test` builtin you already know how to create valid assertions in Fishtape 2.

```fish
@test "current directory is home" $PWD = $HOME

@test "math works" 42 -eq (math 41 + 1)

@test "test is a builtin" (contains -- test (builtin -n)) $status -eq 0

for odd in 1 3 5 7 9
    @test "$odd is not an even number" (
        contains -- $odd (seq 10 | awk '!($0%2)')
    ) $status -eq 0
end

@test "git_is_dirty shows changes not staged for commit" (
    pushd /path/to/some/dirty/git/repo
    git_is_dirty
    echo $status
    popd
) = 1
```

Notice that there is no reason you couldn't write the last test from above as follows (if you prefer):

```fish
pushd /path/to/some/dirty/git/repo
git_is_dirty
@test "git_is_dirty shows changes not staged for commit" $status = 1
popd
```

---

## Issue History
- Use `@test` instead of `test` https://github.com/jorgebucaran/fish-tape/issues/31#issuecomment-460995673

**Comment by edouard-lopez** [comment]
Sound nice.

I will recommend to use the command substitution syntax `test "description" ( … )` in order to isolate test from one another. The last example, with code outside, could have side effects on following test case.
I also reckon the former allow one to use `local` variables but not the letter (I'm on mobile so didn't check this)

**Comment by jorgebucaran** [comment]
@edouard-lopez To isolate your test you have two options.

1. Use a `begin..end` block:

```fish
begin
    pushd /path/to/some/dirty/git/repo
    git_is_dirty
    test "git_is_dirty shows changes not staged for commit" $status = 1
    popd
end
```

2. Use command substitution:

```fish
test "git_is_dirty shows changes not staged for commit" (
    pushd /path/to/some/dirty/git/repo
    git_is_dirty
    echo $status
    popd
) = 1
```

**Comment by jorgebucaran** [comment]
Instead of overloading the `test` builtin I propose using a different syntax for creating tests, e.g. `assert` or `@test`. I prefer `@test` (to take advantage of syntax highlighting). 

This helps make clear when you are writing a test or using the `test` builtin for something else.

```fish
if test "$version" = 3.0.0
    @test "Has some file" -f somefile
end
```

**Comment by edouard-lopez** [comment]
BATS, the test framework for bash [use `@test` syntax](https://github.com/bats-core/bats-core/blob/master/README.md) too.

**Comment by jorgebucaran** [comment]
🎉 I'm done implementing everything. See the changelog:  
- https://github.com/jorgebucaran/fishtape/releases/tag/2.0.0
