### ISSUE TITLE
fish_indent reformatting broke tests

### ISSUE THREAD

**Issue by edouard-lopez** [jorgebucaran/fishtape#32]
**related:** lunaryorn/vscode-fish-ide#6

---

I'm using `fish_indent` through [`vscode-fish-ide`](https://github.com/lunaryorn/vscode-fish-ide) which reformat test file as follows:

```diff
 test "set my_var default value"
-  'default_value' = (
+'default_value' = (
     __pure_set_default my_var 'default_value'
     echo $my_var
-  )
+    )
 end
```

After formatting my tests fails:

```
❯ fishtape tests/__pure_set_default.test.fish
TAP version 13
not ok 1 set my_var default valuedefault_value
  ---
    operator: fail
    expected: '= or !='
    received: '= default_value '
  ...
not ok 2 skip setting value if default already existsdefault_value
  ---
    operator: fail
    expected: '= or !='
    received: '= default_value '
  ...
```

**Comment by jorgebucaran** [comment]
@edouard-lopez Yes, this is a known issue and there is no solution as far as I can see. Fishtape test syntax is invalid fish syntax, therefore using `fish_indent` in your tests will break them.

I don't see any point in keeping this issue open as changing `fish_indent` is beyond our power.
