### ISSUE TITLE
Is it possible to do multiple assertions?

### ISSUE THREAD

**Issue by edouard-lopez** [jorgebucaran/fishtape#33]
Is it possible to do multiple assertions? 

:warning: **This doesn't work:**

```fish
test "format seconds to human"
    set --local seconds 1000  # express as milliseconds
    '1s' = ( _pure_format_time (math "1*$seconds") $THRESHOLD)
    '59s' = ( _pure_format_time (math "59*$seconds") $THRESHOLD)
end
```

If so, how can I do it?

**Comment by jorgebucaran** [comment]
@edouard-lopez Nope, it isn't possible.

**Comment by jorgebucaran** [comment]
~~@edouard-lopez No, and I won't be adding this to 2.0. Tests are almost declarative in nature, allowing for fewer bugs and you can always write your imperative code inside a command substitution.~~

~~I was too quick to make up my mind. I may actually add this to 2.0.~~

~~I'm reopening until I have figured it out.~~

Wontfix! 🎉
