### ISSUE TITLE
Make fishtape file compatible with fish_indent

### ISSUE THREAD

**Issue by edouard-lopez** [jorgebucaran/fishtape#34]
**related:** #32, fish-shell/fish-shell#5399

---

From discussion with @jorgebucaran and @faho it appears using fishtape file aren't ~valid~compatible fish file. Hence the problem met while trying to format them with `fish_indent` (cf. #32).

### Rationale

Adopting a ~valid~compatible fish syntax will let us leverage all the tooling related to `fish` and help developers adopt _testing approaches_. So we get better integration and better software quality.

### Fishtape example

```fish
test "current directory is home"
    $HOME = $DIRNAME
end

test "math still works"
    42 -eq (math 41 + 1)
end

test "test is a builtin"
    "test" = (builtin -n)
end

test "no odds are evens"
    1 3 5 7 != (
        for i in (seq $n)
            if test (math $i%2) = 0
                echo $i
            end
        end
        )
end
```

### Roadblocks

Can we list the roadblocks that prevent `fishtape` file from being ~valid~compatible fish file ?

* [ ] `test` already has a specific meaning in fish, and it does not start blocks. [`test` is a keyword](https://github.com/fish-shell/fish-shell/blob/366c21ca47dce1e2da08a13654ca4729c0d931c8/src/parser_keywords.cpp#L27-L29) in fish 3.0

**Comment by edouard-lopez** [comment]
Note that I might lack some insight in both `fishtape` and `fish`.

Addressing the use of `test`, it seems straightforward to re-write test case as function, _e.g._ prefixed by `test_`. Thus, we can _easily_ evolve the [awk script to match `function test_`](https://github.com/jorgebucaran/fishtape/blob/master/fishtape.fish#L100) and leave the test body untouched.

For instance, we could write _test.fish_:

```
function test_current_directory_is_home
    $HOME = $DIRNAME
end

function test_math_still_works
    42 -eq (math 41 + 1)
end
```

Neither `source test.fish` nor `fish test.fish` throw error.

**Comment by jorgebucaran** [comment]
@edouard-lopez I am sure you're already aware of this, but I should point out that [this](https://github.com/jorgebucaran/fishtape/issues/34#issuecomment-446110403) is not valid fish either.

**Comment by edouard-lopez** [comment]
Sure but `fish` doesn't complain about it until we call the function.
```
❯ source /tmp/fishtape.fish
❯ test_current_directory_is_home/tmp/fishtape.fish (line 1): Variables may not be used as commands. In fish, please define a function or use 'eval $HOME'.
in function “test_current_directory_is_home”
called on standard input
❯ test_math_still_works
42: command not found
in function “test_math_still_works”
        called on standard input
```

I update the issue to target compatibility instead of validity. Do you think it's an attainable goal?

**Comment by jorgebucaran** [comment]
> I update the issue to target compatibility instead of validity. 

Thanks, makes more sense. 👍 

> Do you think it's an attainable goal?

It's doable, but I don't find the suggestion very entertaining. I'm still open to discussing it, but I'd much rather look at other syntax ideas (if you must really attain compatibility with `fish_indent`)

**Comment by edouard-lopez** [comment]
Using `begin; [COMMANDS...;] end` you can't source or execute the file as the code inside `begin` is executed. But you don't seem to source or execute test file and again it's simple to achieve.

Anyway it could be:

```fish
begin "say_hello"
    echo Hello $argv
end
```

```fish
begin test_say_hello
    $HOME = $DIRNAME
end
```

```fish
begin test:say_hello
    echo Hello $argv
end
```

Is there other alternative syntax you can think of?

**Comment by jorgebucaran** [comment]
@edouard-lopez All of those look good, also:

```fish
begin test "is home"
    $HOME = $DIRNAME
end
```

**Comment by edouard-lopez** [comment]
Good one. However [vscode-fish-ide](https://github.com/lunaryorn/vscode-fish-ide) show a syntax error:

![selection_217](https://user-images.githubusercontent.com/1212392/49857531-11a97a80-fdf3-11e8-8480-0ff2fcd5db06.png)

> Variables may not be used as commands. In fish, please define a function or use 'eval $HOME'.

For reference, it's not the case with the `function`
![selection_218](https://user-images.githubusercontent.com/1212392/49857584-3867b100-fdf3-11e8-98b1-8a9e166fbff4.png)

**Comment by faho** [comment]
>Variables may not be used as commands. In fish, please define a function or use 'eval $HOME'.

Fortunately, that's not true with fish 3.0 anymore, so you can just upgrade to [the 3.0 beta](https://github.com/fish-shell/fish-shell/releases/tag/3.0b1) and that bit should be gone.

/plug

------

So... what you two seem to be discussing is how to make this _look_ like fish-script.

That solves the immediate concern that fish_indent indents it "wrong", but it's still essentially invalid fish-script. You're still saving this as ".fish", and `fish some-tape-test.fish` would do something nonsensical.

E.g.

```fish
begin test "is home"
    $HOME = $DIRNAME
end
```

will test if "is home" is a non-empty string, throw away the result, then try to run $HOME as a command with the arguments "=" and "$DIRNAME" (post-3.0) or print an error that variables aren't allowed as commands (pre-3.0).

Why not either invent syntax whole-cloth and call the scripts ".tape", or find a way to make this working fish-script, just with some convenience functions?

**Comment by jorgebucaran** [comment]
Thanks for chiming in @faho.

@edouard-lopez I've been wanting to rewrite fishtape for a while now. When I do, it will be less pretentious and I'll try to find some common ground.

**Comment by jorgebucaran** [comment]
@edouard-lopez I've updated #31 with the new syntax I have in mind. Feedback welcome. 🙏

**Comment by jorgebucaran** [comment]
@edouard-lopez Fishtape tests are now compatible with `fish_indent`. See the changelog:

* https://github.com/jorgebucaran/fishtape/releases/tag/2.0.0
