### ISSUE TITLE
Support conditional test

### ISSUE THREAD

**Issue by edouard-lopez** [jorgebucaran/fishtape#36]
Pure support several version of `fish` (`2.5` to `3.0.0`). However some of our tests are only meaningful on some version of the platform.

To manage this we wrap those tests in a `if…end` block, e.g. [`_pure_prompt_ssh_host.test.fish`](https://github.com/rafaelrinaldi/pure/blob/363af84279102d519ceec8495c78d4a59c199310/tests/_pure_prompt_ssh_host.test.fish#L32-L40):

```fish
if fish_version_at_least '3.0.0'
test "_pure_prompt_ssh_host: use native \$hostname"
    (
        set pure_color_ssh_host (set_color grey)

        _pure_prompt_ssh_host > /dev/null
    ) $status -eq 0
end
end
```

This work as expected but look messy, a decorator would be a lot more elegant, _e.g._:

```fish
# fish_version_at_least 3.0.0
test "_pure_prompt_ssh_host: use native \$hostname"
    …
end
```

**Comment by jorgebucaran** [comment]
@edouard-lopez Is this related to https://github.com/jorgebucaran/fish-tape/issues/34?

**Comment by edouard-lopez** [comment]
Nope, but that a feature request for next release :stuck_out_tongue:

**Comment by jorgebucaran** [comment]
@edouard-lopez Sure it isn't related? Why can't you do this:

```fish
if fish_version_at_least '3.0.0'
  test "_pure_prompt_ssh_host: use native \$hostname"
    (
        set pure_color_ssh_host (set_color grey)

        _pure_prompt_ssh_host > /dev/null
    ) $status -eq 0
  end
end
```

**Comment by edouard-lopez** [comment]
That's what I do but I would prefer a decorator

**Comment by jorgebucaran** [comment]
@edouard-lopez I think I get it now. You are asking for a pre-processor feature to sieve out tests if they are above or below a specific fish version (or based on the status code after running some arbitrary function) and the proposed syntax is a comment.

**Comment by edouard-lopez** [comment]
Correct.

**Comment by jorgebucaran** [comment]
@edouard-lopez ~~I don't think writing conditional tests like are commonplace enough to justify adding a new feature to Fishtape~~. Instead of adding a special feature for this, I suggest we use regular fish code:

```fish
if fish_version_equals_or_is_above 3.0.0
    @test "something" (
        actual operator expected
    )
end
```
