### ISSUE TITLE
Multiple assertions per test

### ISSUE THREAD

**Issue by edouard-lopez** [jorgebucaran/fishtape#37]
Sorry to open an issue but #33 is locked, I can't comment there. 

I've been playing with `PowerShell` and it's test framework `Pester`:

> The convention is to assert a single expectation for each `It` block.

Adding support for multiple assertions might not be worth the time and complexity it will add. Sure it can be annoying when you repeat context between tests but does it happens that often?

**Comment by jorgebucaran** [comment]
@edouard-lopez I'm still experimenting, we'll see. I'll check Pester.

I'm tracking everything related to Fishtape 2 in #31. You can write your feedback there.
