### ISSUE TITLE
Missing $DIRNAME in fishtape 2.0.0

### ISSUE THREAD

**Issue by edouard-lopez** [jorgebucaran/fishtape#39]
**related:** [`2.0.0`](https://github.com/jorgebucaran/fishtape/releases/tag/2.0.0), #38 

---

Thanks for the new release, I haven't made the switch yet, but look forward to it.

In the [release note for `2.0.0`](https://github.com/jorgebucaran/fishtape/releases/tag/2.0.0) you mention removing `$DIRNAME` variable. That annoying, cause I'm using it a on [every test files for `pure`](https://github.com/rafaelrinaldi/pure/blob/1fabe247ce13a1cb4d3de3a219f0116f6af3bb43/tests/) to import function under test, like:

    source $DIRNAME/../functions/_pure_prompt_first_line.fish
 
Sure it's possible to use `$filename` however such a name is **prone to conflict** and makes **code a less readable**:

    source (dirname $filename)/../functions/_pure_prompt_first_line.fish

BATS as a series of [special variables](https://github.com/bats-core/bats-core#special-variables) prefixed by `$BATS_TEST_` (_e.g._ `$BATS_TEST_DIRNAME`).

I reckon namespacing is a must have, and would love to see `dirname` come back :heart: 

Some namespace ideas:

```
$fishtape_test_dirname
$ft_test_dirname
$_test_dirname
```

**Comment by jorgebucaran** [comment]
@edouard-lopez I disagree on code readability, but I'm curious to know how `$filename` is prone to conflicts? Recall that tests run in their own subshell.

Your `source` trick will not work, because `$filename` is really just the name, not the full path, so I'm positive about adding `$dirname` back.

`$dirname` → `/Users/foo/bar`
`$filename` → `test.fish`

What about also?

`$pathname` → `/Users/foo/bar/test.fish`

Too much? :)

**Comment by edouard-lopez** [comment]
Readability is not that bad indeed.

In several scripts I wrote, I rename files and use `$filename` as the variable name that contains the filename extracted from a path. Sure the subshell might prevent conflict, but shouldn't we know it's a fishtape variable and not one from our script?

I tend to prefer `$filepath` over `$pathname`.
To have both `$dirname`, `$filename` and `$pathname` seem a bit redundant.

**Comment by jorgebucaran** [comment]
@edouard-lopez Like this?

- `$fishtape_dirname` → `/Users/foo/bar`
- `$fishtape_filename` → `test.fish`

Any ideas for more variables?

**Comment by edouard-lopez** [comment]
LGTM.

No other requirement for me at the moment.

**Comment by jorgebucaran** [comment]
Added in https://github.com/jorgebucaran/fishtape/commit/b195bc15de838887a153e6ad50555a04085ce307 ([here](https://github.com/jorgebucaran/fishtape/commit/b195bc15de838887a153e6ad50555a04085ce307#diff-46c22218eb70820bd57b590bc258c2d9R108)).

In the end I went with`$current_dirname` and `$current_filename` instead. 

Release notes coming up later! 👋

**Comment by jorgebucaran** [comment]
[Release Notes](https://github.com/jorgebucaran/fishtape/releases/tag/2.1.0)
