### ISSUE TITLE
Conditional test not running

### ISSUE THREAD

**Issue by edouard-lopez** [jorgebucaran/fishtape#42]
In `pure` we have some test cases conditioned by the `fish` version running. However, while migrating to `2.1.0` they stop working. 

For instance, I got no output for the following

```fish
if fish_version_below '3.0.0'
    @test "_pure_prompt_ssh: displays 'user@hostname' when on SSH connection" (
       …
    ) = 0
end
```

However, if I add an `echo whatever` in the `if` block then I got some output

> ok 2 _pure_prompt_ssh: displays 'user@hostname' when on SSH connection

```fish
if fish_version_below '3.0.0'
    echo whatever
    @test "_pure_prompt_ssh: displays 'user@hostname' when on SSH connection" (
       …
    ) = 0
end
```

**Comment by jorgebucaran** [comment]
@edouard-lopez You need to silence `fish_version_below`.

```fish
if fish_version_below '3.0.0' >/dev/null
    echo whatever
    @test "_pure_prompt_ssh: displays 'user@hostname' when on SSH connection" (
       …
    ) = 0
end
```

**Comment by jorgebucaran** [comment]
@edouard-lopez You need to silence `fish_version_below`.

```fish
if fish_version_below '3.0.0' >/dev/null
    @test "_pure_prompt_ssh: displays 'user@hostname' when on SSH connection" (
       …
    ) = 0
end
```

The problem is `fish_version_below` doesn't add newlines to its output, distorting test results, which Fishtape is unable to parse. 

```
fish_version_below 4.0.0
only fish <4.0.0: ⏎
```

As a rule of thumb, don't write to stdout inside your test files unless you are going to capture that output in a variable or do it inside a command substitution.

**Comment by edouard-lopez** [comment]
I updated the code to print to `stderr`, that fixes it. 

However, I get messed-up outputs which I reckon are due to the tests being run as background jobs. So the output is no more prepend to the test result.

Is there a way to sync the `fish_version_below` with its test output?

**Comment by jorgebucaran** [comment]
`@mesg` is your friend. It's described (briefly) in the [Usage](https://github.com/jorgebucaran/fishtape/blob/f62d14719e476dc1e2b530450aae273af141115b/README.md#usage) section in the docs.

My `fish_version_below` would only set the exit status code to `0` or `1` without writing to stdout or stderr. 

Then I'd do something like this:

```fish
if fish_version_below 3.0.0
    echo "fish $version"
    @test "_pure_prompt_ssh: displays 'user@hostname' when on SSH connection" (...) = 0
end
```
