### ISSUE TITLE
Feature Request: oh-my-fish support

### ISSUE THREAD

**Issue by simonrouse9461** [jorgebucaran/fishtape#45]
It would be nice if you can also make it an oh-my-fish plugin.

**Comment by jorgebucaran** [comment]
@simonrouse9461 Did you try `omf install https://github.com/jorgebucaran/fishtape`?

**Comment by jorgebucaran** [comment]
@simonrouse9461 Oh My Fish shouldn't have any problems installing Fishtape. Try `omf install https://github.com/jorgebucaran/fishtape`. 

If you mean adding Fishtape to the Oh My Fish package repository instead, you should send a PR to that repository.
