### ISSUE TITLE
Exclude test file

### ISSUE THREAD

**Issue by edouard-lopez** [jorgebucaran/fishtape#55]
On `pure` I have unit tests and some integration testing for the installation method. Often I would like to exclude them from the test run.

Currently, I do:

```fish
fishtape tests/*.test.fish
# make build-pure-on test-pure-on FISH_VERSION=3.1.2 CMD="fishtape tests/*.test.fish"
```

But I would like to be able to do:

```fish
fishtape tests/*.test.fish --exclude=pure_tools_installer.test.fish
```

Is that a possible feature for the next rewrite?

**Comment by edouard-lopez** [comment]
I tried 

	  ls tests/*.test.fish | grep -v installer | fishtape

But it fails on every file with:

	  TAP version 13
	  fish: The file “tests/fish_greeting.test.fish” is not executable by this user
	  tests/fish_greeting.test.fish
	  ^
	  fish: The file “tests/fish_mode_prompt.test.fish” is not executable by this user
	  tests/fish_mode_prompt.test.fish
	  ^
	  …

**Comment by jorgebucaran** [comment]
You can do this easily with just Fish builtins.

```fish
fishtape (string match --invert tests/{pure_tools_installer,*}.test.fish)
```
or

```fish
fishtape (string match --invert tests/pure_tools_installer.test.fish tests/*.test.fish)
```

Let me know if that is working for you, as I'd prefer to keep Fishtape as minimal as possible.

**Comment by edouard-lopez** [comment]
Work great, thanks!

**Comment by jorgebucaran** [comment]
Alternatively, you may consider renaming `pure_tools_installer.test.fish` to `.pure_tools_installer.fish`.
