### ISSUE TITLE
test vs tests for directory name

### ISSUE THREAD

**Issue by PatrickF1** [jorgebucaran/fishtape#57]
Hi Jorge, sorry if this is a bit too nit-picky, but I was wondering on your thoughts on whether plugins that use fishtape should put their tests in a dir called `test` or `tests`? I was thinking `tests` since all the other traditional fish files are plural (functions, completions, fish_plugins, fish_variables). However, in this plugin you called it `test`. Now I'm not sure what the consensus is. What do you think?

**Comment by jorgebucaran** [comment]
Good question. I prefer `test` and use it everywhere, not just in Fish.

**Comment by jorgebucaran** [comment]
Good question. I prefer `test` and use it everywhere, not just in Fish.

But this is probably a convention I carried over from the JavaScript world, which is irrelevant in Fish. I'm willing to change everything to `tests` if we can make a good argument for it. 

- [x] Many `fish` files are plural: functions, completions, fish_plugins, fish_variables.
- [x] [Fish](https://github.com/fish-shell/fish-shell/tree/master/tests) uses `tests`.
- [x] Tide, Pure, Spacefish, Fzf.fish use `tests`.
 
What else do you have?

**Comment by PatrickF1** [comment]
Have you done a broad survey of fish plugins with tests to see what they've done? I'm assuming you have so know more than me. The only other plugin I've found not written by you that uses Fishtape is by Tide, and Ilan uses tests. See https://github.com/IlanCosman/tide/tree/main/functions/tide/tests

**Comment by jorgebucaran** [comment]
[Pure](https://github.com/rafaelrinaldi/pure) and [Spacefish](https://github.com/matchai/spacefish) use Fishtape as well (not the latest yet, though), and they all use `tests`, not `test` too.

**Comment by PatrickF1** [comment]
Well, there's my argument then. I'm going to use `tests` for now but can be convinced to change if other people change too. Thanks Jorge!

**Comment by jorgebucaran** [comment]
Good enough for me! 🙌
