### ISSUE TITLE
Option to stylize output

### ISSUE THREAD

**Issue by PatrickF1** [jorgebucaran/fishtape#61]
Hi, I understand one of the point of TAP is that you can combine arbitrary producers with consumers/reporters. However, there doesn't seem to be an up-to-date and low-dependency TAP reporter at https://github.com/sindresorhus/awesome-tap#reporters. So, I'm stuck with the default unstyled output of fishtape currently.

Would it be possible to add a flag to fishtape such as `--color` to simple use red for errors, green for successes? And the flag can be off by default so it won't break integrations with reporters.

**Comment by jorgebucaran** [comment]
@PatrickF1 What do you mean by an up-to-date and low-dependency reporter? What about [`tap-difflet`](https://github.com/namuol/tap-difflet) or [`tap-diff`](https://github.com/axross/tap-diff)?

**Comment by PatrickF1** [comment]
I was hoping for something I could just clone and run, like a shell script. Another concern with them is they're both at least 2 years inactive. But I suppose since GH Actions makes installing npm packages pretty easy and the TAP output doesn't change so it's fine. Thanks!
