### ISSUE TITLE
Only try to execute all fish files found as tests

### ISSUE THREAD

**Issue by PatrickF1** [jorgebucaran/fishtape#62]
Hi @jorgebucaran, I love how you've supported me as I try to make the most of fishtape and I now have one more request if you don't mind.

I'd like to store my tests as such:
```
tests/
  _resources/ # contains files used by my tests, none of them are .fish files
  test_suite_1
    test1.fish
    test2.fish
  test_suite_2
    test3.fish
    test4.fish
```
Right now if I execute `fishtape tests/*/*`, I get `fishtape: Invalid file or file not found: _resources/...`.

Would it be a good idea to just try to execute all the .fish files found rather than failing if a non .fish file is found?

**Comment by jorgebucaran** [comment]
Try `tests/*/*.fish`.

**Comment by PatrickF1** [comment]
Oh wow didn’t realize you can do .fish with double wildcards. Thanks! I know this is a feature built into Fish and not fishtape specific, but IMO this might be worth including in the readme.

**Comment by jorgebucaran** [comment]
See also https://fishshell.com/docs/current/#wildcards-globbing

> IMO this might be worth including in the readme

Maybe supplementing an existing section or adding a new one, e.g., "Running tests" with examples. I'm open to this. 👍
