### ISSUE TITLE
No way to specify fish arguments

### ISSUE THREAD

**Issue by kidonng** [jorgebucaran/fishtape#63]
For example, there is no way to let fish run tests in interactive mode (`fish --interactive`).

**Comment by jorgebucaran** [comment]
Interesting. Didn't think of it.

**Comment by PatrickF1** [comment]
@jorgebucaran what are your thoughts about adding this? I could really use it for the purposes of https://github.com/PatrickF1/fzf.fish/pull/180 and I image many other plugins that rely on fisher as well.

**Comment by jorgebucaran** [comment]
Yeah, I'm basically fine with this. 👍

**Comment by kidonng** [comment]
Actually we just need to wrap `fish` with a function, since fishtape [calls plain `fish`](https://github.com/jorgebucaran/fishtape/blob/e6e5fc23dd062ee5ed11828951bf2c85d6798db5/functions/fishtape.fish#L97) instead of `comamnd fish`.

I assume this works well enough so closing.

**Comment by PatrickF1** [comment]
Thanks for figuring out that trick, Xuan.
